import { Category } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'classroom',
    title: 'Classroom',
    color: 'blue',
    icon: '🏫',
    items: [
      { id: 'c1', word: 'Pencil', emoji: '✏️' },
      { id: 'c2', word: 'Book', emoji: '📖' },
      { id: 'c3', word: 'Scissors', emoji: '✂️' },
      { id: 'c4', word: 'Notebook', emoji: '📓' },
      { id: 'c5', word: 'Ruler', emoji: '📏' },
      { id: 'c6', word: 'Door', emoji: '🚪' },
      { id: 'c7', word: 'Window', emoji: '🪟' },
      { id: 'c8', word: 'School Bag', emoji: '🎒' },
      { id: 'c9', word: 'Desk', emoji: '🪑' }, // Using chair/seat for desk context
      { id: 'c10', word: 'Trash Can', emoji: '🗑️' },
    ],
  },
  {
    id: 'nationalities',
    title: 'Nationalities',
    color: 'red',
    icon: '🌍',
    items: [
      { id: 'n1', word: 'Turkey', emoji: '🇹🇷' },
      { id: 'n2', word: 'Japan', emoji: '🇯🇵' },
      { id: 'n3', word: 'USA', emoji: '🇺🇸' },
      { id: 'n4', word: 'Germany', emoji: '🇩🇪' },
      { id: 'n5', word: 'France', emoji: '🇫🇷' },
      { id: 'n6', word: 'Italy', emoji: '🇮🇹' },
      { id: 'n7', word: 'Spain', emoji: '🇪🇸' },
      { id: 'n8', word: 'UK', emoji: '🇬🇧' },
      { id: 'n9', word: 'China', emoji: '🇨🇳' },
      { id: 'n10', word: 'Russia', emoji: '🇷🇺' },
    ],
  },
  {
    id: 'freetime',
    title: 'Free Time',
    color: 'green',
    icon: '🎮',
    items: [
      { id: 'h1', word: 'Swimming', emoji: '🏊' },
      { id: 'h2', word: 'Reading', emoji: '📖' },
      { id: 'h3', word: 'Drawing', emoji: '🎨' },
      { id: 'h4', word: 'Singing', emoji: '🎤' },
      { id: 'h5', word: 'Dancing', emoji: '💃' },
      { id: 'h6', word: 'Football', emoji: '⚽' },
      { id: 'h7', word: 'Basketball', emoji: '🏀' },
      { id: 'h8', word: 'Cycling', emoji: '🚴' },
      { id: 'h9', word: 'Video Games', emoji: '🎮' },
      { id: 'h10', word: 'Chess', emoji: '♟️' },
    ],
  },
  {
    id: 'food',
    title: 'Food & Drinks',
    color: 'amber',
    icon: '🍔',
    items: [
      { id: 'f1', word: 'Apple', emoji: '🍎' },
      { id: 'f2', word: 'Banana', emoji: '🍌' },
      { id: 'f3', word: 'Bread', emoji: '🍞' },
      { id: 'f4', word: 'Ice Cream', emoji: '🍦' },
      { id: 'f5', word: 'Pizza', emoji: '🍕' },
      { id: 'f6', word: 'Water', emoji: '💧' },
      { id: 'f7', word: 'Milk', emoji: '🥛' },
      { id: 'f8', word: 'Egg', emoji: '🥚' },
      { id: 'f9', word: 'Cake', emoji: '🍰' },
      { id: 'f10', word: 'Cookie', emoji: '🍪' },
    ],
  },
  {
    id: 'myday',
    title: 'My Day',
    color: 'purple',
    icon: '🌅',
    items: [
      { id: 'd1', word: 'Wake up', emoji: '🥱' },
      { id: 'd2', word: 'Brush Teeth', emoji: '🪥' },
      { id: 'd3', word: 'Shower', emoji: '🚿' },
      { id: 'd4', word: 'Breakfast', emoji: '🥞' },
      { id: 'd5', word: 'School', emoji: '🏫' },
      { id: 'd6', word: 'Study', emoji: '📝' },
      { id: 'd7', word: 'Play', emoji: '🛝' },
      { id: 'd8', word: 'Sleep', emoji: '🛌' },
      { id: 'd9', word: 'Get Dressed', emoji: '👕' },
      { id: 'd10', word: 'Wash Hands', emoji: '🧼' },
    ],
  },
];